### ISSUE TITLE
Weather Forecast Card Not Properly Displayed in Mobile UI

### ISSUE THREAD

**Issue by Mefisto04** [adaharshsingh/Propacity#14]
### **Description**:
- **Problem**: On mobile devices, the weather forecast card is not properly contained within the main container, causing layout issues. The card appears misaligned and overlaps with other elements.
- **Screenshot**: 
![image](https://github.com/user-attachments/assets/87574e6b-7cf1-42b2-a31b-e78dd84a04db)

  
This problem affects the user experience on smaller screens, making it difficult for users to read the weather forecast data properly.

### **Proposed Solution**:
- Adjust the CSS to ensure the weather forecast card fits within the container in mobile view.
- Implement responsive design rules for small screens to maintain proper spacing and alignment.

### **Additional context**:
- Please assign this issue to me, and kindly add the Hacktoberfest tag for tracking.

**Comment by adaharshsingh** [comment]
Sure ! Go Ahead..........

**Comment by AnujKshatriya** [comment]
Is this issue resolved? if not then can i work on it?

**Comment by adaharshsingh** [comment]
The issue is kindda resolved; the reason why issue is still open because of the header; 
you can open a new issue about the header , that its just white ; and give it more personality, add effects etc.
you can also work on the issue you mentioned and make a pull request ;If its better than now i will merge it
![Screenshot 2024-10-06 124730](https://github.com/user-attachments/assets/d4d401db-3cdc-4ed4-94f2-8da7dad2c5f3)

**Comment by AnujKshatriya** [comment]
Should I change color of Navbar according to weather state ?

**Comment by adaharshsingh** [comment]
do whatever you think will make it better ;only restriction is to make sure it matches with existing theme;
make it another issue

**Comment by AnujKshatriya** [comment]
Okay sure

**Comment by Mefisto04** [comment]
@adaharshsingh you can merge this one so that my changes will help him to enhance the ui of the webapp.
