### ISSUE TITLE
 Center Alignment of Components in the Translucent Black Box

### ISSUE THREAD

**Issue by adaharshsingh** [adaharshsingh/Propacity#29]
The components such as the 5-day weather forecast, current weather card, city recommendation, and current location button are not properly aligned in the translucent black box. These elements should be centered both vertically and horizontally within the box to improve the layout and user experience.

### Current Behavior:

- The components (5-day weather forecast, current weather card, city recommendation, and current location button) are not centrally aligned.
- They may appear off-center or unevenly spaced within the translucent black background.

### Expected Behavior:
All components should be centrally aligned within the translucent black box.

- Horizontally: Each component should be horizontally centered.
- Vertically: The components should be vertically centered as a group within the black box.

**Comment by RishabhSri17** [comment]
Hi @adaharshsingh, I would be more than happy to work on this. Could you please assign this issue to me so I can start the implementation right away?

**Comment by adaharshsingh** [comment]
Go Ahead!!

**Comment by RishabhSri17** [comment]
I am working on the assigned task #29 and have made several updates to achieve the requirement that all components should be centrally aligned within the translucent black box.

Attached are screenshots taken at different breakpoints for review.
![Screenshot 2024-10-08 045359](https://github.com/user-attachments/assets/d42bb8f6-ce53-4c81-9067-10bdf1f185b0)
![Screenshot 2024-10-08 045318](https://github.com/user-attachments/assets/7ed8baf0-1f03-430b-b092-41252dbc8e35)
![Screenshot 2024-10-08 045252](https://github.com/user-attachments/assets/d348c3ba-ddf8-4075-9cde-d9209381a91b)
![Screenshot 2024-10-08 045446](https://github.com/user-attachments/assets/d8e12750-135a-4629-a9db-dbf3aad580f6)

I'm waiting for you to merge PR #31 , so that I can view the changes and work accordingly.

**Comment by adaharshsingh** [comment]
yeah that seems nice , You can make the PR when you are ready;

**Comment by RishabhSri17** [comment]
Hi @adaharshsingh , I had also fixed the issue of the overlapping of content in the bottom ,under footer ,

Screenshots -
![Screenshot 2024-10-08 143447](https://github.com/user-attachments/assets/15ace228-8c83-4fb0-ab7a-aa0541a84b36)
![Screenshot 2024-10-08 143524](https://github.com/user-attachments/assets/3fbc3864-5997-4336-86af-224bf54c0cea)

Can I make the PR now?

**Comment by adaharshsingh** [comment]
Yeah , I will be able to review it better after you make a PR;
And The current header is different from your header

**Comment by RishabhSri17** [comment]
Should I close my PR #33 , check the header part then merge it?
